=== Khmelov/JD2019-03-11/src/by/it/vasiliuk/jd02_09/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.vasiliuk.it.by/"
        xmlns:my="http://jd02_09.vasiliuk.it.by/"
        elementFormDefault="qualified">
    <element name="users">
        <complexType>
            <sequence>
                <element
                        name="user"
                        type="my:TypeOfUser"
                        minOccurs="1"
                        maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="TypeOfUser">
        <sequence>
            <element name="login" type="string" />
            <element name="password" type="string" />
            <element name="email" type="string" />
            <element name="ads" type="my:TypeOfAds" />
        </sequence>
    </complexType>


    <complexType name="TypeOfAds">
        <sequence>
            <element name="ad"
                     type="my:TypeOfAd"
                     minOccurs="1"
                     maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="TypeOfAd">
        <all>
            <element name="description" type="string" />
            <element name="deadline" type="string" />
            <element name="Editor" type="integer" />
            <element name="Creator" type="positiveInteger" />
            <element name="logger" type="positiveInteger" />
            <element name="regularity" type="positiveInteger"/>
            <element name="project_tasks" type="my:TypeOfPrice" />
        </all>
    </complexType>

    <complexType name="TypeOfPrice">
        <simpleContent>
            <extension base="double">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>


</schema>

=== Khmelov/JD2019-03-11/src/by/it/vasiliuk/jd02_09/users+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="http://jd02_09.vasiliuk.it.by/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://jd02_09.vasiliuk.it.by/ ../jd02_07/users.xsd">
    <user>
        <login>Vasya</login>
        <password>qwerty</password>
        <email>vasya@gmail.com</email>
        <ads>
            <ad>
                <description>Task_tools</description>
                <deadline>Minsk, Pushkin street,55</deadline>
                <Editor>9</Editor>
                <Creator>12</Creator>
                <logger>3</logger>
                <regularity>9</regularity>
                <project_tasks currency="USD">17500</project_tasks>
            </ad>
            <ad>
                <description>Best blocks of flat in Pinsk</description>
                <deadline>Pinsk, Kolotushkin street, 12</deadline>
                <Editor>4</Editor>
                <Creator>7</Creator>
                <logger>1</logger>
                <regularity>7</regularity>
                <project_tasks currency="USD">10300</project_tasks>
            </ad>
        </ads>
    </user>
    <user>
        <login>Flight_core</login>
        <password>notqwer</password>
        <email>free_me@tut.by</email>
        <ads>
            <ad>
                <description>Small place in Minsk</description>
                <deadline>Minsk, Hykalo street, 17</deadline>
                <Editor>2</Editor>
                <Creator>6</Creator>
                <logger>2</logger>
                <regularity>8</regularity>
                <project_tasks currency="BYN">3500</project_tasks>
            </ad>
        </ads>
    </user>
</users>
